
all:
	@echo "Not yet implemented!"

alu-test:
	@echo "************************************************************"
	@echo Executing alu-test...
	@iverilog -Iinclude alu/*.v ../src/alu/*.v -o $(BINDIR)/alu-test
	@$(BINDIR)/alu-test
	@echo Finished alu-test.
	@echo "************************************************************"
clean:
	@echo "Not yet implemented!"
